import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import MainHeader from "@/components/MainHeader/MainHeader";

const artegraSans = localFont({
  src: [
    {
      path: "./fonts/ArtegraSansExRegular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Taucer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={artegraSans.className}>
        <MainHeader />
        <main>{children}</main>
        <footer>footer</footer>
      </body>
    </html>
  );
}
